// <auto-generated />
using FlashCards.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashCards.Migrations
{
    [DbContext(typeof(DeckDbContext))]
    partial class DeckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FlashCards.Data.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BackData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("FronData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("FlashCards.Data.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AmountOfCards")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Decks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfCards = 340,
                            Title = "New card"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfCards = 350,
                            Title = "New card1"
                        },
                        new
                        {
                            Id = 3,
                            AmountOfCards = 60,
                            Title = "New card2"
                        },
                        new
                        {
                            Id = 4,
                            AmountOfCards = 8,
                            Title = "New card3"
                        },
                        new
                        {
                            Id = 5,
                            AmountOfCards = 10,
                            Title = "New card4"
                        },
                        new
                        {
                            Id = 6,
                            AmountOfCards = 70,
                            Title = "New card5"
                        },
                        new
                        {
                            Id = 7,
                            AmountOfCards = 70,
                            Title = "New card6"
                        },
                        new
                        {
                            Id = 8,
                            AmountOfCards = 15,
                            Title = "New card7"
                        },
                        new
                        {
                            Id = 9,
                            AmountOfCards = 20,
                            Title = "New card8"
                        },
                        new
                        {
                            Id = 10,
                            AmountOfCards = 12,
                            Title = "New card9"
                        });
                });

            modelBuilder.Entity("FlashCards.Data.Entities.Card", b =>
                {
                    b.HasOne("FlashCards.Data.Entities.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });
#pragma warning restore 612, 618
        }
    }
}
